name: chip-tool 
summary: Chip Tool Matter Controller
description: Refer to https://snapcraft.io/chip-tool

version: v1.3.0.0+snap

confinement: strict
grade: stable
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /mnt:
    bind: $SNAP_COMMON/mnt

parts:
  matter-sdk:
    plugin: matter-sdk
    matter-sdk-version: v1.3.0.0
      
  chip-tool:
    after: 
      - matter-sdk
    plugin: nil
    override-build: |
      # Prepare the environment for using the SDK
      source $CRAFT_STAGE/matter-sdk-env.sh
      
      # Build the chip tool, which is part of the SDK itself
      SDK_PROJECT=../../matter-sdk/build
      cd $SDK_PROJECT/examples/chip-tool
      gn gen out
      ninja -C out
      
      # List shared libraries
      ldd out/chip-tool

      # Stage the binary distribution
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp out/chip-tool $CRAFT_PART_INSTALL/bin/chip-tool
    build-packages:
      - git
      - gcc
      - g++
      - pkg-config
      - libssl-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libavahi-client-dev
      - ninja-build
      - python3-venv
      - python3-dev
      - python3-pip
      - libgirepository1.0-dev
      - libcairo2-dev
      - libreadline-dev
      - generate-ninja

apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-observe
      - process-control
    environment:
      # Replace the path for chip-tool configuration files
      TMPDIR: "/mnt"
