name: chip-tool 
summary: Chip Tool Matter Controller
description: Refer to https://snapcraft.io/chip-tool
adopt-info: connectedhomeip

confinement: strict
grade: stable
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  local:
    plugin: nil
    source: snap/local
    override-build: |
      cp -rv bin $SNAPCRAFT_PART_INSTALL/

  connectedhomeip:
    plugin: nil
    build-environment:
      - BUILD_METADATA: snap
      - CHIP_TAG: v1.3.0.0
    override-pull: |
      # shallow clone the project and its submodules
      git clone https://github.com/project-chip/connectedhomeip.git --depth=1 --branch=$CHIP_TAG .
      scripts/checkout_submodules.py --shallow --platform linux
      
      # prefix the snap version with the upstream tag, or fall back to the commit hash
      UPSTREAM_VERSION=$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)
      craftctl set version=$UPSTREAM_VERSION+$BUILD_METADATA

  chip-tool:
    after: [connectedhomeip]
    plugin: nil
    override-build: |

      mkdir -p $CRAFT_PART_INSTALL/bin

      cd ../../connectedhomeip/src

      # To avoid activation errors, don't treat unset variables as error
      set +u 

      # Bootstrap with minimal "build" requirements
      source ./scripts/setup/bootstrap.sh --platform build

      # Build the chip tool
      ./scripts/examples/gn_build_example.sh examples/chip-tool ./build-examples
      
      cp build-examples/chip-tool $CRAFT_PART_INSTALL/bin/
    build-packages:
      - git
      - gcc
      - g++
      - pkg-config
      - libssl-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libavahi-client-dev
      - ninja-build
      - python3-venv
      - python3-dev
      - python3-pip
      - libgirepository1.0-dev
      - libcairo2-dev
      - libreadline-dev
      - generate-ninja

apps:
  chip-tool:
    command-chain: [bin/set-tmp-dir.sh]
    command: bin/chip-tool
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-observe
      - process-control
