name: Snap Builder
run-name: ${{ github.actor }} is building the ${{ github.repository }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: build
      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
