name: Build, test and publish snap

on:
  schedule:
    - cron: "20 2 * * 1"  # Monday morning 02:20 UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  ARTIFACT_AMD64: chip-tool_${{ github.run_number}}_amd64
  ARTIFACT_ARM64: chip-tool_${{ github.run_number}}_arm64

jobs:
  build-amd64:
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_AMD64 }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
          
  test-amd64:
    needs: build-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Download locally built snap
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_AMD64 }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.*'
          cache: false

      - name: Run tests
        shell: bash
        working-directory: tests
        env:
          SKIP_TEARDOWN_REMOVAL: true
          LOCAL_SERVICE_SNAP: ../${{ needs.build-amd64.outputs.snap }}
        run: |
          go test -failfast -p 1 -timeout 30m -v

      - name: Upload snap logs
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: tests/logs/*.log

  publish-amd64:
    # Only publish if we are on the main branch
    if: github.ref == 'refs/heads/main'
    needs: [build-amd64, test-amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Download locally built snap
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_AMD64 }}

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ needs.build-amd64.outputs.snap }}
          release: latest/edge

  build-arm64:
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    runs-on: Ubuntu_ARM64_4C_16G_01
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_ARM64 }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

  publish-arm64:
    # Only publish if we are on the main branch
    if: github.ref == 'refs/heads/main'
    # For now depend on the amd64 tests to gate arm64 publishing
    needs: [build-arm64, test-amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Download locally built snap
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_ARM64 }}

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ needs.build-arm64.outputs.snap }}
          release: latest/edge
