name: Snap CI

on:
  # schedule:
  #   - cron: "20 2 * * 1" # Monday morning 02:20 UTC
  push:
  #   branches: [main]
  pull_request:
  #   branches: [main]
  # Allow manual trigger
  workflow_dispatch:

env:
  ARTIFACT_AMD64: chip-tool_${{ github.run_number}}_amd64
  ARTIFACT_ARM64: chip-tool_${{ github.run_number}}_arm64

jobs:
  matrix-build:
    strategy:
      matrix:
        runner: ["ubuntu-latest", [self-hosted, ARM64, Linux]]
    runs-on: ${{ matrix.runner }}

    # outputs:
    #   snap: ${{ steps.snapcraft.outputs.snap }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug print
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

    #   - name: Build snap
    #     uses: snapcore/action-build@v1
    #     id: snapcraft

    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #         name: ${{ env.ARTIFACT_AMD64 }}
    #         path: ${{ steps.snapcraft.outputs.snap }}
    #         if-no-files-found: error

  promote:
    needs: [matrix-build]
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        run: echo "Promoting"
